// A vast collection of options for the premium generator suite

export const PREMIUM_STYLES: string[] = [
    'Default', 'Photorealistic', 'Digital Art', 'Anime', 'Fantasy Art', 'Sci-Fi', '3D Render', 'Cinematic', 'Surrealism', 'Steampunk', 
    'Gothic', 'Abstract', 'Watercolor', 'Impressionism', 'Art Deco', 'Art Nouveau', 'Ukiyo-e', 'Pixel Art', 'Vaporwave', 'Glitch Art', 
    'Low Poly', 'Concept Art', 'Matte Painting', 'Comic Book', 'Claymation', 'Pop Art', 'Minimalist', 'Cyberpunk', 'Biopunk', 'Dieselpunk', 
    'Solarpunk', 'Sketch', 'Vintage Photography', 'Double Exposure', 'Baroque', 'Cubism', 'Rococo', 'Neoclassicism', 'Romanticism', 'Realism', 
    'Post-Impressionism', 'Fauvism', 'Expressionism', 'Dadaism', 'Bauhaus', 'Suprematism', 'Constructivism', 'Abstract Expressionism', 
    'Op Art', 'Psychedelic Art', 'Street Art', 'Graffiti', 'Tattoo Art', 'Tribal Art', 'Celtic Art', 'Egyptian Hieroglyphs', 'Mayan Glyphs', 
    'Islamic Calligraphy', 'Chinese Ink Wash', 'Pointillism', 'Collage', 'Assemblage', 'Frottage', 'Decalcomania', 'Fumage', 'Grattage', 
    'Sgraffito', 'Tenebrism', 'Linocut', 'Woodcut', 'Etching', 'Aquatint', 'Mezzotint', 'Lithography', 'Screen Printing', 'Airbrush', 
    'Stained Glass', 'Mosaic', 'Terracotta', 'Kirigami', 'Origami', 'Papercraft', 'Calligraphy', 'Pyrography', 'Body Painting', 
    'Installation Art', 'Land Art', 'Light and Space', 'Kinetic Art', 'Sound Art', 'Video Art', 'Generative Art', 'Algorithmic Art', 'Fractal Art', 'ASCII Art',
    'Synthwave', 'Retrowave', 'Outrun', 'Chibi', 'Kawaii', 'Manga Screentone', 'Infographic', 'Blueprint', 'Technical Drawing', 'Anatomical Drawing',
    'Botanical Illustration', 'Architectural Sketch', 'ISO Metric', 'Hard Surface Modeling', 'Sculpting', 'Figurine', 'Diorama', 'Tilt-Shift',
    'Pinhole Photography', 'Lomography', 'Cyanotype', 'Daguerreotype', 'Ambrotype', 'Albumen Print', 'Autochrome Lumière', 'Infrared Photography',
    'Long-Exposure Photography', 'Macrophotography', 'Astrophotography', 'Light Painting', 'Holography', 'Lenticular Print', 'Anaglyph 3D',
    'Cross-View 3D', 'Stereoscopy', 'Photogrammetry', 'Volumetric Lighting', 'Ray Tracing', 'Path Tracing', 'Global Illumination', 'Ambient Occlusion',
    'Cel Shading', 'Gouache', 'Tempera', 'Fresco', 'Encaustic Painting', 'Casein Painting', 'Action Painting', 'Color Field Painting',
    'Hard-Edge Painting', 'Lyrical Abstraction', 'Tachisme', 'Art Informel', 'COBRA', 'Fluxus', 'Situationist International', 'Lettrism',
    'Neo-Dada', 'Nouveau Réalisme', 'Arte Povera', 'Minimalism', 'Post-Minimalism', 'Conceptual Art', 'Performance Art', 'Happening',
    'Video Installation', 'Net Art', 'Post-Internet Art', 'BioArt', 'EcoArt', 'Hyperrealism', 'Photorealism', 'Magic Realism', 'Social Realism',
    'Socialist Realism', 'Capitalist Realism', 'Metaphysical Painting', 'Precisionism', 'Regionalism', 'American Scene Painting', 'Ashcan School',
    'Hudson River School', 'Barbizon School', 'Pre-Raphaelite Brotherhood', 'Symbolism', 'Aestheticism', 'Decadence', 'Japonisme',
    'Orientalism', 'Primitivism', 'Folk Art', 'Outsider Art', 'Art Brut', 'Naive Art', 'Visionary Art', 'Lowbrow Art', 'Pop Surrealism',
    'Stuckism', 'Superflat', 'Toyism', 'Transavanguardia', 'Neo-Expressionism', 'Young British Artists', 'Leipzig School', 'De Stijl',
    'Orphism', 'Rayonism', 'Vorticism', 'Futurism', 'Tonalism', 'Luminism', 'Academic Art', 'Victorian Era Art', 'Edwardian Era Art',
    'Arts and Crafts Movement', 'Jugendstil', 'Vienna Secession', 'Mughal Painting', 'Persian Miniature', 'Ottoman Miniature',
    'Byzantine Art', 'Gothic Art', 'Romanesque Art', 'Carolingian Art', 'Viking Art', 'Insular Art', 'Anglo-Saxon Art', 'Merovingian Art',
    'Scythian Art', 'Thracian Art', 'Etruscan Art', 'Minoan Art', 'Mycenaean Art', 'Cycladic Art', 'Ancient Greek Art', 'Roman Art',
    'Hellenistic Art', 'Biedermeier', 'Classicism', 'Mannerism', 'High Renaissance', 'Early Renaissance', 'International Gothic',
    'Indian Art', 'African Art', 'Oceanic Art', 'Indigenous Australian Art', 'Native American Art', 'Mesoamerican Art', 'Andean Art',
    'Risograph Print', 'Dot Matrix Print', 'Wireframe', 'Vector Art', 'Voxel Art', 'Pixel Sorting', 'Databending', 'Circuit Bending', 'Decopunk'
];

export const PREMIUM_MOODS: string[] = [
    'Default', 'Happy', 'Sad', 'Energetic', 'Calm', 'Mysterious', 'Ominous', 'Dreamy', 'Epic', 'Romantic', 'Tense', 'Serene', 'Melancholic', 'Whimsical', 
    'Nostalgic', 'Majestic', 'Anxious', 'Ethereal', 'Foreboding', 'Jubilant', 'Tranquil', 'Chaotic', 'Desolate', 'Hopeful', 'Playful', 'Gloomy', 
    'Somber', 'Awestruck', 'Sublime', 'Haunting', 'Thrilling', 'Peaceful', 'Solemn', 'Suspenseful', 'Ecstatic', 'Euphoric', 'Content', 'Pensive', 
    'Reflective', 'Contemplative', 'Meditative', 'Spiritual', 'Sacred', 'Divine', 'Infernal', 'Demonic', 'Hellish', 'Heavenly', 'Angelic', 'Idyllic', 
    'Pastoral', 'Bucolic', 'Arcadian', 'Utopian', 'Dystopian', 'Apocalyptic', 'Post-Apocalyptic', 'Noir', 'Gritty', 'Raw', 'Visceral', 'Primal', 
    'Savage', 'Feral', 'Wild', 'Untamed', 'Civilized', 'Sophisticated', 'Elegant', 'Refined', 'Polished', 'Ornate', 'Lavish', 'Opulent', 'Decadent', 
    'Luxurious', 'Austere', 'Spartan', 'Ascetic', 'Stark', 'Bleak', 'Barren', 'Lush', 'Verdant', 'Fertile', 'Abundant', 'Vibrant', 'Vivacious',
    'Lively', 'Animated', 'Spirited', 'Dynamic', 'Static', 'Still', 'Motionless', 'Frozen', 'Petrified', 'Rigid', 'Stiff', 'Fluid', 'Flowing',
    'Liquid', 'Malleable', 'Elastic', 'Flexible', 'Supple', 'Gentle', 'Tender', 'Delicate', 'Fragile', 'Vulnerable', 'Exposed', 'Harsh',
    'Brutal', 'Cruel', 'Merciless', 'Ruthless', 'Aggressive', 'Violent', 'Turbulent', 'Tempestuous', 'Raging', 'Furious', 'Enraged', 'Irate',
    'Wrathful', 'Vengeful', 'Spiteful', 'Malevolent', 'Malicious', 'Wicked', 'Sinister', 'Nefarious', 'Evil', 'Benevolent', 'Kind', 'Compassionate',
    'Merciful', 'Forgiving', 'Generous', 'Charitable', 'Altruistic', 'Heroic', 'Valiant', 'Brave', 'Courageous', 'Gallant', 'Fearless',
    'Dauntless', 'Intrepid', 'Timid', 'Shy', 'Bashful', 'Reticent', 'Hesitant', 'Reluctant', 'Apprehensive', 'Worried', 'Frightened', 'Scared',
    'Terrified', 'Horrified', 'Petrified', 'Panicked', 'Hysterical', 'Frantic', 'Agitated', 'Restless', 'Fidgety', 'Jittery', 'Nervous',
    'Edgy', 'Jumpy', 'Startled', 'Surprised', 'Astonished', 'Amazed', 'Stunned', 'Dumbfounded', 'Bewildered', 'Confused', 'Puzzled',
    'Baffled', 'Perplexed', 'Disoriented', 'Lost', 'Adrift', 'Aimless', 'Purposeful', 'Determined', 'Resolute', 'Steadfast', 'Unwavering',
    'Ambitious', 'Driven', 'Motivated', 'Inspired', 'Creative', 'Imaginative', 'Innovative', 'Ingenious', 'Resourceful', 'Clever', 'Witty',
    'Humorous', 'Comical', 'Amusing', 'Hilarious', 'Laughable', 'Ridiculous', 'Absurd', 'Nonsensical', 'Silly', 'Goofy', 'Zany', 'Wacky',
    'Bizarre', 'Weird', 'Strange', 'Odd', 'Peculiar', 'Quirky', 'Eccentric', 'Unconventional', 'Unorthodox', 'Heretical', 'Blasphemous',
    'Reverent', 'Pious', 'Devout', 'Faithful', 'Loyal', 'Devoted', 'Dedicated', 'Committed', 'Passionate', 'Ardent', 'Fervent', 'Zealous',
    'Apathetic', 'Indifferent', 'Unconcerned', 'Detached', 'Aloof', 'Distant', 'Cold', 'Frigid', 'Icy', 'Glacial', 'Warm', 'Cozy', 'Comfortable',
    'Snug', 'Secure', 'Safe', 'Protected', 'Guarded', 'Defensive', 'Paranoid', 'Suspicious', 'Wary', 'Cautious', 'Prudent', 'Careful'
];

export const PREMIUM_LIGHTING: string[] = [
    'Default', 'Cinematic', 'Golden Hour', 'Blue Hour', 'Neon Noir', 'Studio Lighting', 'Dramatic', 'Soft Light', 'Hard Light', 'Backlight', 'Rim Light', 
    'Volumetric', 'Chiaroscuro', 'Dappled Light', 'Rembrandt', 'Split Lighting', 'Ambient', 'Crepuscular Rays', 'God Rays', 'Caustic', 'Bioluminescent', 
    'Glowing', 'Iridescent', 'Silhouette', 'High-key', 'Low-key', 'Underwater', 'Candlelight', 'Moonlight', 'Overcast', 'Harsh Sunlight', 'Stage Lighting', 
    'Firelight', 'Long Exposure', 'Disco Lights', 'Laser Show', 'Northern Lights', 'Starlight', 'City Lights', 'Streetlights', 'Lamplight', 'Flashlight', 
    'Headlights', 'Searchlights', 'Spotlight', 'Floodlight', 'Blacklight', 'Ultraviolet', 'Infrared', 'X-ray', 'Cosmic Rays', 'Solar Flare', 'Supernova', 
    'Nebula Glow', 'Strobe Light', 'Light Painting', 'Bokeh', 'Lens Flare', 'Anamorphic Flare', 'Glare', 'Haze', 'Fog', 'Mist', 'Smoke', 'Steam',
    'Key Light', 'Fill Light', 'Kicker Light', 'Practical Light', 'Motivated Light', 'Available Light', 'Natural Light', 'Artificial Light', 'Tungsten Light',
    'Daylight', 'Cloudy Sky', 'Partly Cloudy', 'Direct Sunlight', 'Shade', 'Open Shade', 'Dusk', 'Dawn', 'Twilight', 'Magic Hour', 'Window Light',
    'Diffused Light', 'Bounced Light', 'Reflected Light', 'Scattered Light', 'Directional Light', 'Omnidirectional Light', 'Point Light', 'Area Light',
    'Linear Light', 'Spot Light', 'IES Profile', 'Gobo', 'Barn Doors', 'Snoot', 'Grid', 'Softbox', 'Octabox', 'Beauty Dish', 'Umbrella',
    'Scrim', 'Flag', 'Cutter', 'Gobo Arm', 'C-Stand', 'Light Stand', 'Boom Arm', 'Gel', 'Color Temperature', 'Kelvin', 'Warm White',
    'Cool White', 'Neutral White', 'RGB', 'CMYK', 'HSL', 'HSB', 'HSV', 'Lab Color', 'Pantone', 'CRI', 'TLCI', 'Foot-candle', 'Lux', 'Lumen',
    'Candela', 'Exposure', 'Aperture', 'Shutter Speed', 'ISO', 'EV', 'Stops', 'Dynamic Range', 'HDR', 'LDR', 'Gamma Correction', 'LUT',
    'White Balance', 'Color Cast', 'Color Grading', 'Color Correction', 'Vignette', 'Light Leak', 'Film Grain', 'Noise', 'Chromatic Aberration',
    'Halation', 'Bloom', 'Glow', 'Sparkle', 'Twinkle', 'Shimmer', 'Flicker', 'Pulsating Light', 'Flashing Light', 'Rotating Light', 'Beacon',
    'Lighthouse', 'Lantern', 'Torch', 'Campfire', 'Bonfire', 'Fireworks', 'Explosion', 'Muzzle Flash', 'Laser Beam', 'Plasma Glow', 'Energy Arc',
    'Force Field', 'Magic Aura', 'Holy Aura', 'Unholy Aura', 'Eldritch Glow', 'Ghostly Light', 'Phantom Light', 'Will-o\'-the-wisp', 'Foxfire',

    'Electric Spark', 'Static Discharge', 'Lightning Strike', 'Ball Lightning', 'St. Elmo\'s Fire', 'Aurora Borealis', 'Aurora Australis',
    'Zodiacal Light', 'Gegenschein', 'Airglow', 'Light Pollution', 'Skyglow', 'Tyndall Effect', 'Rayleigh Scattering', 'Mie Scattering', 'Refraction',
    'Diffraction', 'Interference', 'Polarization', 'Doppler Effect', 'Redshift', 'Blueshift', 'Cherenkov Radiation', 'Synchrotron Radiation',
    'Bremsstrahlung', 'Black-body Radiation', 'Incandescence', 'Fluorescence', 'Phosphorescence', 'Luminescence', 'Chemiluminescence',
    'Triboluminescence', 'Sonoluminescence', 'Radioluminescence', 'Electroluminescence', 'Cathodoluminescence', 'Photoluminescence', 'Thermoluminescence',
    'Crystalloluminescence', 'Lyoluminescence', 'Mechanoluminescence', 'Pyroluminescence', 'Shadows', 'Core Shadow', 'Cast Shadow', 'Form Shadow',
    'Attached Shadow', 'Occlusion Shadow', 'Contact Shadow', 'Umbra', 'Penumbra', 'Antumbra', 'Terminator', 'Contrast', 'High Contrast', 'Low Contrast',
    'Tonal Range', 'Midtones', 'Highlights', 'Specular Highlight', 'Blown-out Highlight', 'Crushed Blacks', 'Clipped Blacks', 'Exposure Bracketing'
];

export const PREMIUM_COLORS: string[] = [
    'Default', 'Vibrant', 'Monochromatic', 'Pastel', 'Sepia', 'Black and White', 'Warm Tones', 'Cool Tones', 'Cyberpunk Neon', 'Earthy Tones', 'Technicolor', 
    'Duotone', 'Tritone', 'Analogous', 'Complementary', 'Split-Complementary', 'Triadic', 'Tetadic', 'Jewel Tones', 'Muted Tones', 'Grayscale', 'Infrared', 
    'Thermal', 'Psychedelic', 'Fluorescent', 'Iridescent Hues', 'Metallic Gold', 'Metallic Silver', 'Metallic Copper', 'Metallic Bronze', 'Chrome', 'Autumnal Palette', 
    'Winter Palette', 'Spring Palette', 'Summer Palette', 'Sunset Hues', 'Deep Sea Tones', 'Galactic Nebula', 'Acidic', 'Radioactive', 'Viridian', 'Cerulean', 
    'Magenta', 'Chartreuse', 'Vermilion', 'Sienna', 'Umber', 'Ochre', 'Indigo', 'Amethyst', 'Emerald', 'Ruby', 'Sapphire', 'Topaz', 'Onyx', 'Pearl', 'Alabaster', 
    'Ivory', 'Ebony', 'Jet Black', 'Vantablack', 'Snow White', 'Ghost White', 'Baby Blue', 'Bubblegum Pink', 'Mint Green', 'Lavender', 'Coral', 'Peach', 'Teal', 
    'Turquoise', 'Cyan', 'Aquamarine', 'Marine', 'Navy', 'Royal Blue', 'Sky Blue', 'Azure', 'Cobalt', 'Ultramarine', 'Periwinkle', 'Mauve', 'Fuchsia', 'Crimson', 
    'Scarlet', 'Maroon', 'Burgundy', 'Wine', 'Plum', 'Violet', 'Lilac', 'Orchid', 'Salmon', 'Tangerine', 'Apricot', 'Lemon', 'Lime', 'Olive', 'Moss', 
    'Forest Green', 'Pine Green', 'Kelly Green', 'Seafoam', 'Pistachio', 'Sage', 'Khaki', 'Beige', 'Tan', 'Taupe', 'Cream', 'Eggshell', 'Champagne', 'Pewter', 
    'Steel', 'Iron', 'Rust', 'Charcoal', 'Slate', 'Gunmetal', 'Ash', 'Stone', 'Clay', 'Sand', 'Terracotta', 'Brick Red', 'Mustard Yellow', 'Olive Drab',
    'Army Green', 'Midnight Blue', 'Electric Blue', 'Hot Pink', 'Shocking Pink', 'Neon Green', 'Neon Yellow', 'Safety Orange', 'Blaze Orange', 'International Klein Blue',
    'Tiffany Blue', 'Celadon', 'Verdigris', 'Cinnabar', 'Gamboge', 'Tyrian Purple', 'Indian Red', 'Prussian Blue', 'Cobalt Blue', 'Cadmium Yellow',
    'Hansa Yellow', 'Phthalo Green', 'Phthalo Blue', 'Quinacridone Magenta', 'Dioxazine Purple', 'Burnt Sienna', 'Raw Sienna', 'Burnt Umber', 'Raw Umber',
    'Payne\'s Gray', 'Davy\'s Gray', 'Ivory Black', 'Lamp Black', 'Mars Black', 'Titanium White', 'Zinc White', 'Flake White', 'Lead White', 'Bismuth White',
    'Barium White', 'Lithopone', 'Gofun', 'Chalk', 'Gypsum', 'Kaolin', 'Bole', 'Green Earth', 'Lapis Lazuli', 'Malachite', 'Azurite', 'Orpiment',
    'Realgar', 'Hematite', 'Limonite', 'Goethite', 'Smalt', 'Zaffer', 'Egyptian Blue', 'Han Purple', 'Han Blue', 'Maya Blue', 'Scheele\'s Green',
    'Paris Green', 'Emerald Green', 'Verona Green', 'Hooker\'s Green', 'Sap Green', 'Terre Verte', 'Dragon\'s Blood', 'Cochineal', 'Kermes',
    'Madder', 'Saffron', 'Weld', 'Turmeric', 'Annatto', 'Brazilwood', 'Logwood', 'Fustic', 'Quercitron', 'Cutch', 'Gallic Acid', 'Tannin',
    'Woad', 'Isatis Tinctoria', 'Indigofera Tinctoria', 'Persian Berry', 'Stil de Grain', 'Dutch Pink', 'Brown Pink', 'Carmine', 'Rose Madder',
    'Alizarin Crimson', 'Geranium Lake', 'Indian Yellow', 'Naples Yellow', 'Aureolin', 'Gamboge', 'Stil de Grain', 'Van Dyke Brown', 'Asphaltum', 'Bitumen',
    'Mummy Brown', 'Caput Mortuum', 'Venetian Red', 'Pozzuoli Earth', 'Sinopia', 'Flesh Tone', 'Caucasian', 'African', 'Asian', 'Hispanic', 'Native American',
    'Polynesian', 'Melanin', 'Eumelanin', 'Pheomelanin', 'Carotene', 'Hemoglobin', 'Bilirubin', 'Biliverdin', 'Urochrome', 'Porphyrin', 'Chlorophyll',

    'Carotenoid', 'Flavonoid', 'Anthocyanin', 'Betalain', 'Lycopene', 'Zeaxanthin', 'Lutein', 'Astaxanthin', 'Canthaxanthin', 'Phycocyanin',
    'Phycoerythrin', 'Allophycocyanin', 'Bacteriochlorophyll', 'Rhodopsin', 'Iodopsin', 'Melanopsin', 'Cryptochrome', 'Phototropin', 'Phytochrome',
    'Luciferin', 'Luciferase', 'GFP', 'RFP', 'YFP', 'CFP', 'BFP', 'Color palette of Wes Anderson', 'Color palette of Tim Burton', 'Ghibli color palette'
];

export const CAMERA_ANGLES: string[] = [
    'Default', 'Eye-Level Shot', 'Low-Angle Shot', 'High-Angle Shot', 'Birds-Eye View', 'Worms-Eye View', 'Dutch Angle', 'Over-the-Shoulder Shot', 'Point-of-View (POV)', 'Close-Up', 'Extreme Close-Up', 'Medium Shot', 'Long Shot', 'Wide Shot', 'Establishing Shot', 'Drone Shot',
    'Aerial Shot', 'Crane Shot', 'Handheld Shot', 'Steadicam Shot', 'Tracking Shot', 'Dolly Shot', 'Pan', 'Tilt', 'Zoom', 'Dolly Zoom', 'Vertigo Effect', 'Crash Zoom', 'Whip Pan', 'Swish Pan', 'Jib Shot', 'SnorriCam Shot', 'BodyCam Shot', 'GoPro Shot', 'Found Footage', 'Mockumentary Style',
    'Cinéma Vérité', 'Direct Cinema', 'Observational Cinema', 'Fly-on-the-wall', 'Guerilla Filmmaking', 'Static Shot', 'Fixed Frame', 'Locked-off Shot', 'Tripod Shot', 'Monopod Shot', 'Slider Shot', 'Gimbal Shot', 'Ronin Shot', 'MōVI Shot', 'Arc Shot', 'Orbit Shot', '360-degree Shot',
    'Money Shot', 'Hero Shot', 'Glamour Shot', 'Headshot', 'Bust Shot', 'Waist Shot', 'Knee Shot', 'Full Shot', 'Cowboy Shot', 'American Shot', 'Two Shot', 'Three Shot', 'Group Shot', 'Master Shot', 'Insert Shot', 'Cutaway Shot', 'Reaction Shot', 'Noddy Shot', 'Pickup Shot', 'B-roll',
    'A-roll', 'Stock Footage', 'Archival Footage', 'Newsreel', 'Kinescope', 'Telecine', 'Film Look', 'Video Look', 'Digital Look', 'Shot on iPhone', 'Shot on Android', 'DSLR Video', 'Mirrorless Video', 'Cinema Camera', 'IMAX', '70mm', '35mm', '16mm', '8mm', 'Super 8', 'VHS Look',
    'Betamax Look', 'U-matic Look', 'Hi8 Look', 'MiniDV Look', 'DV CAM Look', 'HDV Look', 'AVCHD Look', 'XDCAM Look', 'P2 Look', 'REDCODE RAW Look', 'ArriRaw Look', 'ProRes Look', 'DNxHD Look', 'H.264 Look', 'H.265 Look', 'AV1 Look', 'VP9 Look', 'Theora Look', 'Dirac Look', 'Daala Look',
    'CCTV Footage', 'Security Camera', 'Surveillance Camera', 'Body Worn Camera', 'Dashcam', 'Nanny Cam', 'Spy Cam', 'Hidden Camera', 'Trail Cam', 'Game Cam', 'Camera Trap', 'Thermal Camera', 'Infrared Camera', 'Night Vision', 'X-ray Vision', 'Microscope View', 'Telescope View',
    'Binocular View', 'Periscope View', 'Keyhole View', 'Door Peephole View', 'Cracked Lens', 'Dirty Lens', 'Wet Lens', 'Steamy Lens', 'Frosted Lens', 'Scratched Lens', 'Broken Lens', 'Light Leak', 'Lens Flare', 'Anamorphic Flare', 'Spherical Flare', 'Ghosting', 'Veiling Flare', 'Internal Reflection',
    'Barrel Distortion', 'Pincushion Distortion', 'Mustache Distortion', 'Perspective Distortion', 'Foreshortening', 'Keystoning', 'Converging Verticals', 'Vanishing Point', 'One-Point Perspective', 'Two-Point Perspective', 'Three-Point Perspective', 'Four-Point Perspective',
    'Five-Point Perspective', 'Six-Point Perspective', 'Curvilinear Perspective', 'Spherical Perspective', 'Cylindrical Perspective', 'Panini Projection', 'Stereographic Projection', 'Mercator Projection', 'Gnomonic Projection', 'Orthographic Projection', 'Equirectangular Projection',
    'Cubemap Projection', 'Fisheye Projection', 'Mirror Shot', 'Reflection Shot', 'Selfie', 'Groupie', 'Usie', 'Photobomb', 'Mise-en-scène', 'Tableau', 'Freeze Frame', 'Slow Motion', 'Fast Motion', 'Time-lapse', 'Hyperlapse', 'Bullet Time', 'Go-motion', 'Stop-motion', 'Claymation', 'Pixilation',
    'Puppetoon', 'Rotoscoping', 'Motion Capture', 'Performance Capture', 'Virtual Camera', 'Augmented Reality', 'Virtual Reality', 'Mixed Reality', 'Extended Reality', 'Cross-Reality', 'CGI', 'VFX', 'SFX', 'Matte Painting', 'Digital Matte Painting', 'Glass Shot', 'Shuftan Process', 'Foreground Miniature',
    'Background Miniature', 'Forced Perspective', 'Hanging Miniature', 'Slit-scan', 'Motion Control Photography', 'Optical Printing', 'Rear Projection', 'Front Projection', 'Zoptic', 'Introvision', 'Compositing', 'Alpha Compositing', 'Chroma Key', 'Green Screen', 'Blue Screen', 'Luma Key'
];

export const ARTISTS_MOVEMENTS: string[] = [
    'Default', 'Leonardo da Vinci', 'Michelangelo', 'Rembrandt', 'Vincent van Gogh', 'Pablo Picasso', 'Salvador Dalí', 'Claude Monet', 'Frida Kahlo', 'Andy Warhol', 'H.R. ' +
    'Giger', 'Zdzisław Beksiński', 'Hayao Miyazaki', 'Greg Rutkowski', 'Artgerm', 'Moebius', 'Impressionism', 'Cubism', 'Surrealism', 'Pop Art', 'Art Nouveau', 'Bauhaus',
    'Caravaggio', 'Johannes Vermeer', 'Katsushika Hokusai', 'J.M.W. Turner', 'Gustave Doré', 'Alphonse Mucha', 'Egon Schiele', 'Gustav Klimt', 'Wassily Kandinsky', 'Piet Mondrian',
    'Marcel Duchamp', 'René Magritte', 'M.C. Escher', 'Edward Hopper', 'Georgia O\'Keeffe', 'Norman Rockwell', 'Francis Bacon', 'Jackson Pollock', 'Mark Rothko', 'Willem de Kooning',
    'Roy Lichtenstein', 'Jasper Johns', 'Robert Rauschenberg', 'Jean-Michel Basquiat', 'Keith Haring', 'Banksy', 'Shepard Fairey', 'Takashi Murakami', 'Yayoi Kusama', 'Damien Hirst',
    'Jeff Koons', 'Ansel Adams', 'Henri Cartier-Bresson', 'Robert Capa', 'Dorothea Lange', 'Walker Evans', 'Man Ray', 'Diane Arbus', 'Richard Avedon', 'Irving Penn',
    'Helmut Newton', 'Annie Leibovitz', 'Sebastião Salgado', 'Steve McCurry', 'James Nachtwey', 'Frank Frazetta', 'Boris Vallejo', 'Julie Bell', 'Syd Mead', 'Ralph McQuarrie',
    'Doug Chiang', 'Hajime Sorayama', 'Yoshitaka Amano', 'Katsuhiro Otomo', 'Masamune Shirow', 'Osamu Tezuka', 'Leiji Matsumoto', 'Go Nagai', 'Rumiko Takahashi', 'Naoko Takeuchi',
    'Eiichiro Oda', 'Masashi Kishimoto', 'Tite Kubo', 'Akira Toriyama', 'Kentaro Miura', 'Takehiko Inoue', 'Junji Ito', 'Suehiro Maruo', 'Shintaro Kago', 'Robert Crumb',
    'Jack Kirby', 'Steve Ditko', 'Stan Lee', 'Will Eisner', 'Frank Miller', 'Alan Moore', 'Dave Gibbons', 'Neil Gaiman', 'Dave McKean', 'Mike Mignola', 'Jim Lee', 'Todd McFarlane',
    'Rob Liefeld', 'Alex Ross', 'J. Scott Campbell', 'Adam Hughes', 'Art Spiegelman', 'Daniel Clowes', 'Charles Burns', 'Chris Ware', 'Adrian Tomine', 'Marjane Satrapi',
    'R. Kikuo Johnson', 'Taiyo Matsumoto', 'Inio Asano', 'Shuzo Oshimi', 'Q Hayashida', 'Tsutomu Nihei', 'Hieronymus Bosch', 'Pieter Bruegel the Elder', 'Albrecht Dürer',
    'Hans Holbein the Younger', 'El Greco', 'Diego Velázquez', 'Francisco Goya', 'Édouard Manet', 'Edgar Degas', 'Paul Cézanne', 'Paul Gauguin', 'Henri de Toulouse-Lautrec',
    'Edvard Munch', 'James Ensor', 'Odilon Redon', 'Arnold Böcklin', 'Max Klinger', 'Franz von Stuck', 'Caspar David Friedrich', 'John Constable', 'William Blake', 'Henry Fuseli',
    'Dante Gabriel Rossetti', 'John Everett Millais', 'William Holman Hunt', 'Edward Burne-Jones', 'Aubrey Beardsley', 'John Singer Sargent', 'James McNeill Whistler',
    'Mary Cassatt', 'Berthe Morisot', 'Camille Pissarro', 'Alfred Sisley', 'Georges Seurat', 'Paul Signac', 'Henri Matisse', 'André Derain', 'Georges Braque', 'Juan Gris',
    'Fernand Léger', 'Robert Delaunay', 'Sonia Delaunay', 'Kazimir Malevich', 'El Lissitzky', 'Alexander Rodchenko', 'Vladimir Tatlin', 'Naum Gabo', 'Antoine Pevsner', 'László Moholy-Nagy',
    'Max Ernst', 'Joan Miró', 'Yves Tanguy', 'Max Beckmann', 'George Grosz', 'Otto Dix', 'Käthe Kollwitz', 'Ernst Ludwig Kirchner', 'Erich Heckel', 'Karl Schmidt-Rottluff',
    'Franz Marc', 'August Macke', 'Alexej von Jawlensky', 'Gabriele Münter', 'Paul Klee', 'Lyonel Feininger', 'Oskar Kokoschka', 'Amedeo Modigliani', 'Constantin Brâncuși',
    'Alberto Giacometti', 'Henry Moore', 'Barbara Hepworth', 'Alexander Calder', 'Louise Bourgeois', 'Eva Hesse', 'Donald Judd', 'Carl Andre', 'Dan Flavin', 'Sol LeWitt',
    'Robert Morris', 'Richard Serra', 'Joseph Beuys', 'Nam June Paik', 'Yoko Ono', 'Marina Abramović', 'Chris Burden', 'Vito Acconci', 'Bruce Nauman', 'John Baldessari', 'Ed Ruscha',
    'David Hockney', 'Gerhard Richter', 'Sigmar Polke', 'Anselm Kiefer', 'Georg Baselitz', 'Jörg Immendorff', 'A. R. Penck', 'Markus Lüpertz', 'Francesco Clemente',
    'Sandro Chia', 'Enzo Cucchi', 'Mimmo Paladino', 'Julian Schnabel', 'David Salle', 'Eric Fischl', 'Cindy Sherman', 'Barbara Kruger', 'Jenny Holzer', 'Sherrie Levine', 'Jeff Wall'
];

export const COMPOSITIONS: string[] = [
    'Default', 'Rule of Thirds', 'Golden Ratio', 'Symmetrical', 'Asymmetrical', 'Centered', 'Leading Lines', 'Diagonal', 'Frame within a Frame', 'Pattern and Repetition', 'Minimalist Composition', 'Dynamic Composition',
    'Rule of Odds', 'Rule of Space', 'Negative Space', 'Fill the Frame', 'Isolate the Subject', 'Change Your Point of View', 'Play with Eye Contact', 'Use of Color', 'Use of Light',
    'Use of Shadow', 'Use of Texture', 'Use of Shape', 'Use of Form', 'Use of Line', 'Use of Tone', 'Use of Contrast', 'Use of Balance', 'Radial Balance', 'Symmetrical Balance',
    'Asymmetrical Balance', 'Crystallographic Balance', 'Use of Harmony', 'Use of Unity', 'Use of Variety', 'Use of Emphasis', 'Use of Movement', 'Use of Rhythm', 'Use of Scale',
    'Use of Proportion', 'Use of Perspective', 'Linear Perspective', 'Atmospheric Perspective', 'Aerial Perspective', 'Forced Perspective', 'Use of Depth', 'Shallow Depth of Field',
    'Deep Depth of Field', 'Bokeh', 'Foreground Interest', 'Middleground', 'Background', 'Layering', 'Juxtaposition', 'Subframing', 'Diagonals and Triangles', 'Curves and S-curves',
    'Golden Triangles', 'Golden Spiral', 'Fibonacci Spiral', 'Dynamic Symmetry', 'Armature', 'Baroque Diagonal', 'Sinister Diagonal', 'Coincidental Lines', 'Intersection of Thirds',
    'Dead Center', 'Headroom', 'Lead Room', 'Nose Room', 'Looking Room', 'Walking Room', 'Breathing Room', 'Visual Weight', 'Figure-Ground Relationship', 'Gestalt Principles',
    'Proximity', 'Similarity', 'Continuity', 'Closure', 'Common Fate', 'Good Form', 'Prägnanz', 'Law of Common Region', 'Law of Element Connectedness', 'Law of Synchrony',
    'The Decisive Moment', 'Intentional Camera Movement', 'Panning', 'Tilting', 'Zooming', 'Focus Pull', 'Rack Focus', 'Shallow Focus', 'Deep Focus', 'Soft Focus', 'Split Diopter',
    'Selective Focus', 'Out of Focus', 'In Focus', 'Tack Sharp', 'Motion Blur', 'Light Trails', 'Star Trails', 'The Brenizer Method', 'Panorama', 'Vertorama', 'Stitching', 'Stacking',
    'Focus Stacking', 'Exposure Blending', 'HDR Imaging', 'Tone Mapping', 'Infrared Imaging', 'Ultraviolet Imaging', 'X-ray Imaging', 'Kirlian Photography', 'Schlieren Photography',
    'High-speed Photography', 'Time-slice Photography', 'Bullet-time Photography', 'Scanography', 'Photogram', 'Chemgram', 'Luminogram', 'Solarigraphy', 'Pinhole Camera',
    'Camera Obscura', 'Zone System', 'Dodging and Burning', 'Contrast Masking', 'Unsharp Masking', 'Split Toning', 'Cross Processing', 'Bleach Bypass', 'Solarization', 'Sabattier Effect',
    'Posterization', 'Halftone', 'Duotone', 'Tritone', 'Quadtone', 'Hand-coloring', 'Tinting', 'Toning', 'Cyanotype', 'Van Dyke Brown', 'Albumen Print', 'Salt Print',
    'Platinum Print', 'Palladium Print', 'Gum Bichromate', 'Carbon Print', 'Oil Print', 'Bromoil Process', 'Kallitype', 'Argyrotype', 'Chrysotype', 'Ziatype', 'Ambrotype',
    'Daguerreotype', 'Calotype', 'Talbotype', 'Autochrome', 'Wet-collodion Process', 'Dry-collodion Process', 'Gelatin Silver Process', 'Dye-transfer Process',
    'Cibachrome', 'Ilfochrome', 'Polaroid', 'Instant Film', 'Film Soup', 'Lomography', 'Toy Camera', 'Holga', 'Diana', 'Lensbaby', 'Creative Filter', 'ND Filter', 'Polarizing Filter',
    'UV Filter', 'Color Filter', 'Graduated Filter', 'Star Filter', 'Diffusion Filter', 'Mist Filter', 'Low Contrast Filter', 'Infrared Filter', 'Cross Screen Filter', 'Multi-image Prism',
    'Close-up Lens', 'Diopter', 'Extension Tube', 'Bellows', 'Reversing Ring', 'Teleconverter', 'Speed Booster', 'Focal Reducer', 'Adapter Ring', 'Matte Box', 'Follow Focus'
];

export const ART_MEDIUMS: string[] = [
    'Default', 'Oil Painting', 'Acrylic Painting', 'Watercolor Painting', 'Charcoal Drawing', 'Pencil Sketch', 'Ink Drawing', 'Pastel Art', 'Bronze Sculpture', 'Marble Sculpture', 'Wood Carving', 'Digital Painting', '3D Render', 'Photograph', 'Collage', 'Embroidery',
    'Gouache Painting', 'Tempera Painting', 'Fresco Painting', 'Encaustic Painting', 'Casein Painting', 'Graphite Drawing', 'Colored Pencil Drawing', 'Conté Crayon Drawing', 'Silverpoint Drawing',
    'Metalpoint Drawing', 'Chalk Drawing', 'Sanguine Drawing', 'Carbon Dust Drawing', 'Scratchboard', 'Linocut Print', 'Woodcut Print', 'Etching Print', 'Aquatint Print', 'Mezzotint Print',
    'Lithograph Print', 'Screenprint', 'Monotype', 'Monoprint', 'Drypoint Print', 'Engraving Print', 'Stipple Engraving', 'Photogravure', 'Heliogravure', 'Giclée Print', 'Risograph Print',
    'Clay Sculpture', 'Terracotta Sculpture', 'Porcelain Sculpture', 'Stoneware Sculpture', 'Earthenware Sculpture', 'Glass Sculpture', 'Ice Sculpture', 'Sand Sculpture', 'Bronze Casting',
    'Aluminum Casting', 'Iron Casting', 'Steel Fabrication', 'Welded Sculpture', 'Assemblage Sculpture', 'Found Object Sculpture', 'Kinetic Sculpture', 'Light Sculpture', 'Sound Sculpture',
    'Installation Art', 'Land Art', 'Earthwork', 'Environmental Art', 'Site-specific Art', 'Performance Art', 'Body Art', 'Tattoo Art', 'Textile Art', 'Weaving', 'Tapestry',
    'Knitting', 'Crochet', 'Macramé', 'Quilting', 'Batik', 'Shibori', 'Tie-dye', 'Felting', 'Paper Art', 'Origami', 'Kirigami', 'Papier-mâché', 'Bookbinding', 'Calligraphy',
    'Illuminated Manuscript', 'Jewelry Making', 'Metalsmithing', 'Enameling', 'Lapidary', 'Ceramics', 'Pottery', 'Glassblowing', 'Stained Glass', 'Mosaic', 'Pyrography',
    'Woodturning', 'Marquetry', 'Inlay', 'Leatherworking', 'Taxidermy', 'Bone Carving', 'Ivory Carving', 'Scrimshaw', 'Egg Decorating', 'Pysanka', 'Bonsai', 'Ikebana',
    'Suiseki', 'Penjing', 'Gardening', 'Topiary', 'Floral Design', 'Aquascaping', 'Cymatics', 'Holography', 'Anaglyph', 'Lenticular Art', 'Video Art', 'Animation',
    'Cel Animation', 'Stop Motion Animation', 'Computer Animation', '3D Animation', '2D Animation', 'Motion Graphics', 'Visual Effects', 'Generative Art', 'Algorithmic Art',
    'Fractal Art', 'AI Art', 'Neural Network Art', 'GAN Art', 'Deep Dream', 'Style Transfer', 'Creative Coding', 'Processing', 'p5.js', 'openFrameworks', 'Cinder',
    'TouchDesigner', 'Max/MSP', 'Pure Data', 'SuperCollider', 'ChucK', 'Sonic Pi', 'Virtual Reality Art', 'Augmented Reality Art', 'Mixed Reality Art', 'Interactive Art',

    'BioArt', 'Transgenic Art', 'Ecological Art', 'Street Art', 'Graffiti', 'Mural', 'Stencil', 'Sticker Art', 'Wheatpaste', 'Yarn Bombing', 'Lock On', 'Guerilla Art',
    'Public Art', 'Monument', 'Fountain', 'Architectural Art', 'Faux Painting', 'Trompe-l\'œil', 'Grisaille', 'Marbling', 'Gilding', 'Verre Églomisé', 'Scagliola', 'Cosmatesque',
    'Pietra Dura', 'Micromosaic', 'Decoupage', 'Sospeso Trasparente', 'Quilling', 'String Art', 'Sand Painting', 'Powder Coating', 'Anodizing', 'Electroplating', 'Patination',
    'Airbrushing', 'Spray Painting', 'Digital Illustration', 'Vector Illustration', 'Raster Graphics', 'Pixel Art', 'ASCII Art', 'ANSI Art', 'Voxel Art', 'Photobashing', 'Matte Painting',
    'Concept Art', 'Storyboarding', 'Character Design', 'Environment Design', 'Prop Design', 'Creature Design', 'Vehicle Design', 'Weapon Design', 'UI Design', 'UX Design',
    'Graphic Design', 'Typography', 'Logo Design', 'Branding', 'Poster Design', 'Infographic Design', 'Web Design', 'App Design', 'Game Design', 'Level Design', 'Fashion Design',
    'Costume Design', 'Textile Design', 'Industrial Design', 'Product Design', 'Furniture Design', 'Interior Design', 'Architectural Design', 'Landscape Design', 'Urban Design', 'Stage Design'
];

export const DETAIL_LEVELS: string[] = [
    'Default', 'Hyperdetailed', 'Highly Detailed', 'Intricate Details', 'Photorealistic Detail', 'Simple', 'Minimalist', 'Abstract', 'Vague', 'Impressionistic Detail',
    'Crisp', 'Sharp', 'Clear', 'Precise', 'Fine', 'Delicate', 'Elaborate', 'Ornate', 'Complex', 'Layered', 'Textured', 'Grained', 'Rough', 'Smooth', 'Polished', 'Glossy', 'Matte',
    'Satin', 'Lustrous', 'Iridescent', 'Opalescent', 'Pearlescent', 'Translucent', 'Transparent', 'Opaque', 'Murky', 'Muddy', 'Cloudy', 'Hazy', 'Misty', 'Foggy', 'Smoky', 'Dusty',
    'Gritty', 'Noisy', 'Clean', 'Pristine', 'Immaculate', 'Spotless', 'Flawless', 'Perfect', 'Imperfect', 'Flawed', 'Worn', 'Aged', 'Weathered', 'Distressed', 'Decayed', 'Ruined',
    'Dilapidated', 'Crumbling', 'Eroded', 'Corroded', 'Rusted', 'Patinated', 'Tarnished', 'Faded', 'Bleached', 'Sun-bleached', 'Washed-out', 'Vivid', 'Saturated', 'Rich', 'Deep',
    'Bold', 'Bright', 'Luminous', 'Radiant', 'Glowing', 'Dim', 'Dark', 'Shadowy', 'Gloomy', 'Somber', 'Stark', 'High-contrast', 'Low-contrast', 'Soft', 'Hard', 'Edgy', 'Defined',
    'Undefined', 'Fuzzy', 'Blurry', 'Out of focus', 'In focus', 'Tack-sharp', 'Pin-sharp', 'Microscopic', 'Macroscopic', 'Telescopic', 'Panoramic', 'Wide-angle', 'Close-up', 'Extreme close-up',
    'Loose', 'Tight', 'Sketchy', 'Doodled', 'Scribbled', 'Hatched', 'Cross-hatched', 'Stippled', 'Pointillist', 'Dotted', 'Spotted', 'Speckled', 'Flecked', 'Marbled', 'Veined',
    'Striped', 'Banded', 'Lined', 'Checked', 'Plaid', 'Tartan', 'Gingham', 'Argyle', 'Harlequin', 'Houndstooth', 'Paisley', 'Polka-dotted', 'Ditsy', 'Floral', 'Botanical',
    'Geometric', 'Tribal', 'Ethnic', 'Ikat', 'Batik', 'Shibori', 'Toile', 'Damask', 'Brocade', 'Jacquard', 'Tweed', 'Herringbone', 'Chinoiserie', 'Art Deco pattern', 'Art Nouveau pattern',
    'Psychedelic pattern', 'Op art pattern', 'Camouflage', 'Animal print', 'Leopard print', 'Zebra print', 'Tiger stripe', 'Giraffe spot', 'Snakeskin', 'Crocodile skin', 'Feathers',
 'Fur', 'Hair', 'Scales', 'Skin', 'Flesh', 'Muscle', 'Bone', 'Sinew', 'Cartilage', 'Veins', 'Arteries', 'Nerves', 'Organs', 'Cells', 'Molecules', 'Atoms', 'Quarks', 'Cosmic', 'Galactic',
    'Stellar', 'Nebular', 'Planetary', 'Lunar', 'Solar', 'Terrestrial', 'Aquatic', 'Aerial', 'Subterranean', 'Volcanic', 'Glacial', 'Desert', 'Jungle', 'Forest', 'Mountain', 'Urban',
    'Suburban', 'Rural', 'Industrial', 'Domestic', 'Interior', 'Exterior', 'Architectural', 'Mechanical', 'Biological', 'Geological', 'Meteorological', 'Atmospheric', 'Oceanic',
    'Hydrological', 'Cryospheric', 'Lithospheric', 'Biospheric', 'Anatomical', 'Botanical', 'Zoological', 'Entomological', 'Ornithological', 'Ichthyological', 'Herpetological',
    'Mammalogical', 'Paleontological', 'Archaeological', 'Historical', 'Mythological', 'Theological', 'Philosophical', 'Psychological', 'Sociological', 'Political', 'Economic',
    'Technological', 'Scientific', 'Mathematical', 'Musical', 'Literary', 'Theatrical', 'Cinematic', 'Choreographic', 'Gastronomic', 'Fashionable', 'Ergonomic', 'Aerodynamic'
];

export const TIMES_OF_DAY: string[] = [
    'Default', 'Sunrise', 'Dawn', 'Morning', 'Midday', 'High Noon', 'Afternoon', 'Golden Hour', 'Sunset', 'Dusk', 'Twilight', 'Blue Hour', 'Night', 'Midnight', 'Witching Hour',
    'Predawn', 'Civil Twilight', 'Nautical Twilight', 'Astronomical Twilight', 'Solar Noon', 'Late Afternoon', 'Early Evening', 'Late Evening', 'Dead of Night', 'Small Hours',
    'Wee Hours', 'First Light', 'Last Light', 'Daybreak', 'Sunup', 'Sundown', 'Nightfall', 'Gloaming', 'Eventide', 'Cockcrow', 'Matins', 'Lauds', 'Prime', 'Terce',
    'Sext', 'None', 'Vespers', 'Compline', 'Nocturnes', 'Tenebrae', 'Siesta', 'Teatime', 'Happy Hour', 'Rush Hour', 'Commute', 'Lunchtime', 'Dinnertime', 'Bedtime',
    'Storytime', 'Playtime', 'Naptime', 'School time', 'Work time', 'Leisure time', 'Family time', 'Me time', 'Quiet time', 'Party time', 'Game time', 'Movie time',
    'Reading time', 'Study time', 'Practice time', 'Rehearsal time', 'Performance time', 'Showtime', 'Curtain call', 'Encore', 'Afterparty', 'Hangover', 'Recovery',
    'Weekend', 'Weekday', 'Holiday', 'Vacation', 'Staycation', 'Sabbatical', 'Retirement', 'Childhood', 'Adolescence', 'Adulthood', 'Old age', 'Infancy', 'Toddlerhood',
    'Youth', 'Middle age', 'Senescence', 'Spring', 'Summer', 'Autumn', 'Winter', 'Monsoon', 'Dry season', 'Wet season', 'Hurricane season', 'Tornado season', 'Wildfire season',
    'Pollen season', 'Flu season', 'Tax season', 'Holiday season', 'Wedding season', 'Tourist season', 'Off-season', 'Pre-season', 'Post-season', 'Regular season',
    'Playoffs', 'Championship', 'Super Bowl', 'World Cup', 'Olympics', 'New Year\'s Eve', 'New Year\'s Day', 'Valentine\'s Day', 'St. Patrick\'s Day', 'April Fools\' Day', 'Easter',
    'Mother\'s Day', 'Father\'s Day', 'Independence Day', 'Halloween', 'Thanksgiving', 'Christmas Eve', 'Christmas Day', 'Boxing Day', 'Hanukkah', 'Kwanzaa', 'Diwali',
    'Holi', 'Eid al-Fitr', 'Eid al-Adha', 'Ramadan', 'Passover', 'Rosh Hashanah', 'Yom Kippur', 'Chinese New Year', 'Lunar New Year', 'Solar New Year', 'Solstice',
    'Equinox', 'Perigee', 'Apogee', 'Perihelion', 'Aphelion', 'Eclipse', 'Transit', 'Occultation', 'Conjunction', 'Opposition', 'Syzygy', 'Quadrature', 'Elongation',
    'Meteor shower', 'Comet passing', 'Supernova explosion', 'Black hole formation', 'Big Bang', 'Heat Death', 'Singularity', 'Wormhole opening', 'Time warp', 'Paradox',
    'Déjà vu', 'Flashback', 'Flashforward', 'Dream sequence', 'Hallucination', 'Vision', 'Epiphany', 'Satori', 'Nirvana', 'Enlightenment', 'Apocalypse', 'Ragnarok',
    'Armageddon', 'Judgment Day', 'Doomsday', 'Eschaton', 'Millennium', 'Golden Age', 'Silver Age', 'Bronze Age', 'Iron Age', 'Stone Age', 'Ice Age', 'Jurassic Period',
    'Cretaceous Period', 'Paleozoic Era', 'Mesozoic Era', 'Cenozoic Era', 'Precambrian', 'Hadean', 'Archean', 'Proterozoic', 'Phanerozoic', 'Holocene', 'Pleistocene'
];

export const WEATHER_EFFECTS: string[] = [
    'Default', 'Clear Skies', 'Sunny', 'Overcast', 'Cloudy', 'Partly Cloudy', 'Light Rain', 'Heavy Rain', 'Drizzle', 'Thunderstorm', 'Lightning', 'Light Snow', 'Heavy Snow', 'Blizzard', 'Foggy', 'Misty', 'Hazy', 'Windy', 'Hurricane', 'Tornado',
    'Sun Shower', 'Rainbow', 'Double Rainbow', 'Moonbow', 'Fogbow', 'Halo', 'Sun Dog', 'Light Pillar', 'Glory', 'Brocken Spectre', 'Green Flash', 'Crepuscular Rays',
    'Anticrepuscular Rays', 'Airglow', 'Aurora Borealis', 'Aurora Australis', 'STEVE', 'Sprites', 'Elves', 'Blue Jets', 'Giant Jets', 'St. Elmo\'s Fire', 'Ball Lightning',
    'Sheet Lightning', 'Forked Lightning', 'Cloud-to-ground Lightning', 'Cloud-to-cloud Lightning', 'Anvil Crawler', 'Positive Lightning', 'Superbolt', 'Thunder', 'Hail',
    'Graupel', 'Sleet', 'Freezing Rain', 'Hoarfrost', 'Rime Ice', 'Black Ice', 'Diamond Dust', 'Snowflakes', 'Snowdrift', 'Snowbank', 'Avalanche', 'Glacier', 'Iceberg',
    'Ice Sheet', 'Ice Cap', 'Ice Shelf', 'Ice Cave', 'Ice Flow', 'Ice Jam', 'Frazil Ice', 'Pancake Ice', 'Nilas', 'Grease Ice', 'Shuga', 'Cryosphere', 'Permafrost',
    'Frost Heave', 'Ice Lens', 'Pingo', 'Palsa', 'Thaw', 'Meltwater', 'Runoff', 'Flood', 'Flash Flood', 'Storm Surge', 'Tsunami', 'Seiche', 'Rogue Wave', 'Waterspout',
    'Dust Devil', 'Fire Whirl', 'Steam Devil', 'Haboob', 'Sandstorm', 'Dust Storm', 'Khamsin', 'Simoom', 'Shamal', 'Ghibli', 'Sirocco', 'Foehn Wind', 'Chinook Wind',
    'Santa Ana Winds', 'Diablo Wind', 'Nor\'easter', 'Sou\'wester', 'Polar Vortex', 'Jet Stream', 'Trade Winds', 'Doldrums', 'Horse Latitudes', 'Roaring Forties',
    'Furious Fifties', 'Shrieking Sixties', 'Williwaw', 'Katabatic Wind', 'Anabatic Wind', 'Sea Breeze', 'Land Breeze', 'Mountain Breeze', 'Valley Breeze', 'Monsoon',
    'El Niño', 'La Niña', 'Drought', 'Heatwave', 'Cold Snap', 'Indian Summer', 'White Christmas', 'Acid Rain', 'Smog', 'Vog', 'Air Pollution', 'Ozone Layer',
    'Greenhouse Effect', 'Global Warming', 'Climate Change', 'Microclimate', 'Weather Front', 'Cold Front', 'Warm Front', 'Stationary Front', 'Occluded Front', 'Dry Line',
    'Squall Line', 'Derecho', 'Bow Echo', 'Mesocyclone', 'Supercell', 'Cumulonimbus', 'Cumulus', 'Stratus', 'Cirrus', 'Nimbostratus', 'Altostratus', 'Altocumulus',
    'Cirrostratus', 'Cirrocumulus', 'Lenticular Cloud', 'Pileus Cloud', 'Mammatus Cloud', 'Arcus Cloud', 'Roll Cloud', 'Shelf Cloud', 'Funnel Cloud', 'Wall Cloud',
    'Pyrocumulus', 'Nacreous Cloud', 'Noctilucent Cloud', 'Contrail', 'Virga', 'Precipitation', 'Evaporation', 'Condensation', 'Sublimation', 'Deposition', 'Transpiration',
    'Hydrologic Cycle', 'Barometric Pressure', 'High Pressure System', 'Low Pressure System', 'Anticyclone', 'Cyclone', 'Isobar', 'Isotherm', 'Humidity', 'Dew Point',
    'Relative Humidity', 'Absolute Humidity', 'Specific Humidity', 'Mixing Ratio', 'Saturated', 'Unsaturated', 'Supersaturated', 'Hygrometer', 'Anemometer', 'Wind Vane',
    'Barometer', 'Thermometer', 'Rain Gauge', 'Weather Balloon', 'Radiosonde', 'Weather Satellite', 'Doppler Radar', 'NEXRAD', 'LIDAR', 'SODAR', 'Ceilometer', 'Disdrometer'
];

export const SETTINGS_ENVIRONMENTS: string[] = [
    'Default', 'Enchanted Forest', 'Cyberpunk Cityscape', 'Steampunk Metropolis', 'Post-Apocalyptic Wasteland', 'Underwater Kingdom', 'Alien Planet', 'Deep Space Nebula', 'Volcanic Lair', 'Arctic Tundra', 'Tropical Jungle', 'Sunken Ruins', 'Floating Islands', 'Medieval Castle', 'Futuristic Laboratory',
    'Grand Library', 'Abandoned Asylum', 'Haunted Mansion', 'Bustling Marketplace', 'Serene Monastery', 'Ancient Temple', 'Gladiator Arena', 'Viking Village', 'Wild West Town',
    'Roaring Twenties Speakeasy', 'Victorian London Street', 'World War II Bunker', 'Cold War Spy Hideout', 'Silicon Valley Startup Office', 'International Space Station',
    'Mars Colony', 'Dyson Sphere', 'Ringworld', 'Generation Ship', 'Asteroid Mine', 'Black Hole Accretion Disk', 'Quantum Realm', 'Dreamscape', 'Nightmare Realm',
    'Spirit World', 'Fairy Circle', 'Goblin Market', 'Dragon\'s Hoard', 'Wizard\'s Tower', 'Alchemist\'s Workshop', 'Thieves\' Guild', 'Assassin\'s Stronghold', 'King\'s Court',
    'Emperor\'s Palace', 'Pharaoh\'s Tomb', 'Ziggurat', 'Pyramid', 'Hanging Gardens', 'Colossus of Rhodes', 'Lighthouse of Alexandria', 'Mausoleum at Halicarnassus',
    'Temple of Artemis', 'Statue of Zeus', 'Atlantis', 'El Dorado', 'Shangri-La', 'Avalon', 'Camelot', 'Valhalla', 'Asgard', 'Mount Olympus', 'Hades', 'Tartarus',
    'Elysian Fields', 'Garden of Eden', 'Heaven', 'Hell', 'Purgatory', 'Limbo', 'Nirvana', 'The Matrix', 'Hogwarts', 'Middle-earth', 'Narnia', 'Westeros', 'Hyrule',
    'Mushroom Kingdom', 'Silent Hill', 'Raccoon City', 'Los Santos', 'Vice City', 'Liberty City', 'Capital Wasteland', 'Mojave Wasteland', 'The Commonwealth', 'Skyrim',
    'Morrowind', 'Cyrodiil', 'Pandora', 'Arrakis', 'Tatooine', 'Coruscant', 'Hoth', 'Endor', 'LV-426', 'Cybertron', 'Gallifrey', 'Magrathea', 'Discworld', 'Oz',
    'Wonderland', 'Neverland', 'Fantasia', 'The Grid', 'Tron City', 'Zion', 'Mega-City One', 'Neo-Tokyo', 'Akira', 'Ghost in the Shell', 'Blade Runner', 'Star Trek',
    'Star Wars', 'Dune', 'Lord of the Rings', 'Harry Potter', 'Game of Thrones', 'The Legend of Zelda', 'Super Mario', 'Silent Hill', 'Resident Evil', 'Grand Theft Auto',
    'Fallout', 'The Elder Scrolls', 'Borderlands', 'Doctor Who', 'The Hitchhiker\'s Guide to the Galaxy', 'Alice in Wonderland', 'Peter Pan', 'The NeverEnding Story',
    'Carnival', 'Circus', 'Amusement Park', 'Theme Park', 'Water Park', 'Zoo', 'Aquarium', 'Museum', 'Art Gallery', 'Theater', 'Cinema', 'Concert Hall', 'Opera House',
    'Stadium', 'Arena', 'Racetrack', 'Skatepark', 'Playground', 'Park', 'Garden', 'Botanical Garden', 'Arboretum', 'National Park', 'Wilderness', 'Nature Preserve',
    'Beach', 'Desert', 'Savanna', 'Prairie', 'Steppe', 'Pampas', 'Veldt', 'Taiga', 'Boreal Forest', 'Rainforest', 'Cloud Forest', 'Swamp', 'Marsh', 'Bog', 'Fen',
    'Mangrove', 'Wetland', 'Estuary', 'Delta', 'River', 'Lake', 'Pond', 'Ocean', 'Sea', 'Coral Reef', 'Kelp Forest', 'Hydrothermal Vent', 'Abyssal Plain', 'Trenches',
    'Cave', 'Cavern', 'Grotto', 'Cenote', 'Underground River', 'Lava Tube', 'Crystal Cave', 'Bioluminescent Cave', 'Mountain Range', 'Valley', 'Canyon', 'Gorge', 'Ravine',
    'Plateau', 'Mesa', 'Butte', 'Volcano', 'Geyser', 'Hot Spring', 'Fumarole', 'Mudpot', 'Caldera', 'Crater', 'Impact Crater', 'Badlands', 'Hoodoos', 'Rock Formation',
    'Arch', 'Bridge', 'Natural Bridge', 'Sea Arch', 'Sea Stack', 'Sea Cave', 'Blowhole', 'Fjord', 'Glacier', 'Ice Sheet', 'Ice Cap', 'Ice Field', 'Nunatak', 'Moraine',
    'Drumlin', 'Esker', 'Kame', 'Kettle', 'Outwash Plain', 'Proglacial Lake', 'Terminal Moraine', 'Cirque', 'Arête', 'Horn', 'Hanging Valley', 'U-shaped Valley'
];

export const LENS_TYPES: string[] = [
    'Default', 'Standard Lens (50mm)', 'Wide-Angle Lens (24mm)', 'Ultra Wide-Angle', 'Fisheye Lens', 'Telephoto Lens (200mm)', 'Macro Lens', 'Tilt-Shift Lens', 'Anamorphic Lens', 'Soft Focus Lens',
    'Prime Lens', 'Zoom Lens', 'Pancake Lens', 'Portrait Lens', 'Landscape Lens', 'Street Photography Lens', 'Sports Lens', 'Wildlife Lens', 'Astrophotography Lens', 'Architectural Lens',
    'Cine Lens', 'Medical Lens', 'Industrial Lens', 'UV Lens', 'Infrared Lens', 'X-ray Lens', 'Apochromatic Lens', 'Achromatic Lens', 'Superachromatic Lens', 'Fluorite Lens',
    'Aspherical Lens', 'ED Glass Lens', 'Low Dispersion Lens', 'High Refractive Index Lens', 'Floating Element Lens', 'Internal Focusing Lens', 'Rear Focusing Lens', 'Retrofocus Lens',
    'Tessar Lens', 'Double Gauss Lens', 'Cooke Triplet Lens', 'Petzval Lens', 'Dagor Lens', 'Celcor Lens', 'Heliar Lens', 'Planar Lens', 'Sonnar Lens', 'Biogon Lens', 'Hologon Lens',
    'Distagon Lens', 'Tele-Tessar Lens', 'Vario-Sonnar Lens', 'Lensbaby', 'Pinhole', 'Zone Plate', 'Fresnel Lens', 'Gradient-index Lens', 'Metamaterial Lens', 'Superlens',
    'Perfect Lens', 'Liquid Lens', 'Adaptive Lens', 'Varifocal Lens', 'Parfocal Lens', 'Catadioptric Lens', 'Mirror Lens', 'Reflex Lens', 'Schmidt-Cassegrain Lens',
    'Maksutov-Cassegrain Lens', 'Ritchey-Chrétien Lens', 'Klevtsov-Cassegrain Lens', 'Lurking-Cassegrain Lens', 'Gregorian Telescope', 'Newtonian Telescope',
    'Dobsonian Telescope', 'Refracting Telescope', 'Galilean Telescope', 'Keplerian Telescope', 'Spyglass', 'Monocular', 'Binoculars', 'Opera Glasses', 'Field Glasses',
    'Telescopic Sight', 'Scope', 'Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'Iron Sights', 'Peep Sight', 'Aperture Sight', 'Leaf Sight', 'Tangent Sight',
    'Microscope', 'Compound Microscope', 'Stereo Microscope', 'Confocal Microscope', 'Electron Microscope', 'Scanning Electron Microscope', 'Transmission Electron Microscope',
    'Scanning Tunneling Microscope', 'Atomic Force Microscope', 'Magnifying Glass', 'Loupe', 'Jeweler\'s Loupe', 'Coddington Magnifier', 'Hastings Triplet', 'Wollaston Prism',
    'Nicol Prism', 'Glan-Thompson Prism', 'Glan-Foucault Prism', 'Glan-Taylor Prism', 'Rochon Prism', 'Sénarmont Prism', 'Nomarski Prism', 'Dove Prism', 'Penta Prism',
    'Amici Prism', 'Porro Prism', 'Abbe-Koenig Prism', 'Schmidt-Pechan Prism', 'Beam Splitter', 'Dichroic Mirror', 'Hot Mirror', 'Cold Mirror', 'Pellicle Mirror',
    'First Surface Mirror', 'Concave Mirror', 'Convex Mirror', 'Parabolic Mirror', 'Spherical Mirror', 'Toroidal Mirror', 'Off-axis Paraboloid', 'Mangin Mirror',
    'Corner Reflector', 'Retroreflector', 'Optical Fiber', 'Light Pipe', 'Waveguide', 'Grating', 'Diffraction Grating', 'Echelle Grating', 'Zone Plate', 'Soret Zone Plate',
    'Photon Sieve', 'Optical Cavity', 'Fabry-Pérot Interferometer', 'Mach-Zehnder Interferometer', 'Michelson Interferometer', 'Sagnac Interferometer', 'LIGO',
    'VIRGO', 'KAGRA', 'LISA', 'Hubble Space Telescope', 'James Webb Space Telescope', 'Spitzer Space Telescope', 'Chandra X-ray Observatory', 'Compton Gamma Ray Observatory',
    'Fermi Gamma-ray Space Telescope', 'Kepler Space Telescope', 'TESS', 'GAIA', 'Euclid', 'WFIRST', 'Nancy Grace Roman Space Telescope', 'VLT', 'ELT', 'GMT', 'TMT',
    'Keck Observatory', 'Subaru Telescope', 'Gemini Observatory', 'LBT', 'HET', 'SALT', 'GTC', 'Arecibo Observatory', 'FAST', 'Green Bank Telescope', 'Effelsberg 100-m Telescope',
    'Parkes Observatory', 'Jodrell Bank Observatory', 'ALMA', 'VLA', 'SKA', 'LOFAR', 'Event Horizon Telescope', 'IceCube Neutrino Observatory', 'Super-Kamiokande', 'Sudbury Neutrino Observatory'
];

export const RENDER_ENGINES: string[] = [
    'Default', 'Octane Render', 'V-Ray', 'Redshift', 'Unreal Engine 5', 'Unity Engine', 'Cycles Renderer', 'Arnold Renderer', 'Mental Ray', 'Corona Renderer',
    'Blender Eevee', 'LuxCoreRender', 'Maxwell Render', 'Indigo Renderer', 'Thea Render', 'Kerkythea', 'YafaRay', 'Mitsuba Renderer', 'Appleseed', 'RenderMan',
    '3Delight', 'Gelato', 'FinalRender', 'Brazil R/S', 'Turtle', 'FurryBall', 'Iray', 'KeyShot', 'Marmoset Toolbag', 'Substance Painter', 'Quixel Mixer',
    'ZBrush', 'Mudbox', '3D-Coat', 'Modo', 'Cinema 4D', '3ds Max', 'Maya', 'Houdini', 'LightWave 3D', 'Softimage', 'Blender', 'SketchUp', 'Rhinoceros 3D',
    'SolidWorks', 'CATIA', 'AutoCAD', 'Inventor', 'Fusion 360', 'Creo', 'NX', 'Alias', 'VRED', 'DeltaGen', 'Showcase', 'Navisworks', 'Revit', 'ArchiCAD',
    'Vectorworks', 'MicroStation', 'CityEngine', 'Terragen', 'Vue', 'Bryce', 'Poser', 'DAZ Studio', 'MakeHuman', 'Character Creator', 'iClone', 'Marvelous Designer',
    'CLO 3D', 'Browzwear', 'Style3D', 'Tukatech', 'Lectra', 'Gerber', 'Optitex', 'Adobe Dimension', 'Adobe Stager', 'Adobe Aero', 'Adobe Substance 3D',
    'Foundry Katana', 'Foundry Mari', 'Foundry Nuke', 'Autodesk Flame', 'Autodesk Smoke', 'Blackmagic Fusion', 'DaVinci Resolve', 'Adobe After Effects',
    'Adobe Premiere Pro', 'Final Cut Pro', 'Avid Media Composer', 'Vegas Pro', 'HitFilm', 'Natron', 'Blender VSE', 'Kdenlive', 'Shotcut', 'OpenShot', 'Olive',
    'Flowblade', 'Cinelerra', 'Lightworks', 'Quantel', 'Mistika', 'Baselight', 'Nucoda', 'Scratch', 'Lustre', 'Pablo', 'Rio', 'Symphony', 'DS', 'Avid DS',
    'Shake', 'Combustion', 'Inferno', 'Flint', 'Flame', 'Illusion', 'Digital Fusion', 'Eyeon Fusion', 'GenerationQ', 'Liberty', 'Freedom', 'Commotion',
    'Matador', 'Jaleo', 'Cineon', 'DPX', 'OpenEXR', 'ACES', 'OCIO', 'Filmlight', 'Technicolor', 'Deluxe', 'Efilm', 'Company 3', 'MPC', 'Weta Digital',
    'ILM', 'DNEG', 'Framestore', 'Sony Pictures Imageworks', 'Digital Domain', 'Pixar', 'Disney Animation', 'DreamWorks Animation', 'Blue Sky Studios',
    'Illumination', 'Laika', 'Aardman Animations', 'Studio Ghibli', 'Kyoto Animation', 'Ufotable', 'Toei Animation', 'Sunrise', 'Bones', 'Madhouse', 'Production I.G',
    'Gainax', 'Trigger', 'CloverWorks', 'A-1 Pictures', 'MAPPA', 'Wit Studio', 'Polygon Pictures', 'Digital Frontier', 'OLM', 'Tatsunoko Production',
    'Pierrot', 'TMS Entertainment', 'Nippon Animation', 'Shin-Ei Animation', 'Xebec', 'Satelight', 'GoHands', 'David Production', 'White Fox', 'Kinema Citrus',
    'Orange', 'Sanzigen', 'Kamikaze Douga', 'Graphinica', 'Lerche', 'Passione', 'Bibury Animation Studios', 'ENGI', 'NUT', 'Studio 3Hz', 'C2C', '8-Bit'
];