// FIX: Implemented the full constants file which was previously missing.
// This provides the necessary data for the UI dropdowns in the ImageGenerator component
// and resolves the module resolution errors.

export const CREATIVE_STYLES: string[] = [
  'Photorealistic',
  'Digital Art',
  'Anime',
  'Fantasy Art',
  'Sci-Fi',
  '3D Render',
  'Cinematic',
  'Surrealism',
  'Steampunk',
  'Gothic',
  'Abstract',
  'Watercolor',
  'Impressionism',
  'Art Deco',
  'Art Nouveau',
  'Baroque',
  'Cubism',
  'Ukiyo-e',
  'Pixel Art',
  'Vaporwave',
  'Glitch Art',
  'Low Poly',
  'Concept Art',
  'Matte Painting',
  'Comic Book Style',
  'Claymation',
  'Pop Art',
  'Minimalist',
  'Cyberpunk',
  'Biopunk',
  'Dieselpunk',
  'Solarpunk',
  'Sketch',
  'Vintage Photography',
  'Double Exposure'
];

export const IMAGEN_BRAIN_RATIOS: { name: string; aspectRatio: "1:1" | "3:4" | "4:3" | "9:16" | "16:9"; className: string }[] = [
  { name: 'Square (1:1)', aspectRatio: '1:1', className: 'aspect-square' },
  { name: 'Portrait (3:4)', aspectRatio: '3:4', className: 'aspect-[3/4]' },
  { name: 'Landscape (4:3)', aspectRatio: '4:3', className: 'aspect-[4/3]' },
  { name: 'Tall (9:16)', aspectRatio: '9:16', className: 'aspect-[9/16]' },
  { name: 'Wide (16:9)', aspectRatio: '16:9', className: 'aspect-[16/9]' },
];

export const MOODS: string[] = [
  'Neutral',
  'Happy',
  'Sad',
  'Energetic',
  'Calm',
  'Mysterious',
  'Ominous',
  'Dreamy',
  'Epic',
  'Romantic',
  'Tense',
  'Serene',
  'Melancholic',
  'Whimsical',
  'Nostalgic',
  'Majestic',
  'Anxious',
  'Ethereal',
  'Foreboding',
  'Jubilant',
  'Tranquil',
  'Chaotic',
  'Desolate',
  'Hopeful',
  'Playful',
  'Gloomy',
  'Somber',
  'Awestruck',
  'Sublime',
  'Haunting',
  'Thrilling',
  'Peaceful',
  'Solemn',
  'Suspenseful'
];

export const LIGHTING_STYLES: string[] = [
  'Neutral',
  'Cinematic Lighting',
  'Golden Hour',
  'Neon Noir',
  'Studio Lighting',
  'Dramatic Lighting',
  'Soft Light',
  'Backlight',
  'Rim Light',
  'Volumetric',
  'Chiaroscuro',
  'Hard Light',
  'Dappled Light',
  'Rembrandt Lighting',
  'Split Lighting',
  'Ambient Light',
  'Crepuscular Rays',
  'Volumetric Rays',
  'Caustic Lighting',
  'Bioluminescent',
  'Glowing',
  'Iridescent',
  'Silhouette',
  'High-key Lighting',
  'Low-key Lighting',
  'Underwater Lighting',
  'Candlelight',
  'Moonlight',
  'Overcast',
  'Harsh Sunlight',
  'Stage Lighting',
  'Firelight',
  'Long Exposure',
  'God Rays'
];

export const COLORS: string[] = [
  'Default',
  'Vibrant',
  'Monochromatic',
  'Pastel',
  'Sepia',
  'Black and White',
  'Warm Tones',
  'Cool Tones',
  'Cyberpunk Neon',
  'Earthy Tones',
  'Technicolor',
  'Duotone',
  'Tritone',
  'Analogous Colors',
  'Complementary Colors',
  'Split-Complementary',
  'Triadic Palette',
  'Tetradic Palette',
  'Jewel Tones',
  'Muted Tones',
  'Grayscale',
  'Infrared',
  'Thermal',
  'Psychedelic',
  'Fluorescent',
  'Iridescent Hues',
  'Metallic Tones',
  'Autumnal Palette',
  'Winter Palette',
  'Spring Palette',
  'Summer Palette',
  'Sunset Hues',
  'Deep Sea Tones',
  'Galactic Nebula Colors'
];
