// FIX: Completed the file content which was truncated and added the missing default export.
import React from 'react';
import MetaTags from '../components/MetaTags';

const DisclaimerPage: React.FC = () => {
  return (
    <>
      <MetaTags
        title="Disclaimer | Seedream ImagenBrainAi"
        description="Disclaimer for Seedream ImagenBrainAi. Understand the terms of use, content ownership, and limitations of our AI-generated content."
        canonicalPath="/disclaimer"
      />
      <div className="max-w-4xl mx-auto prose prose-invert prose-headings:text-green-300 prose-a:text-green-300">
        <h1>Disclaimer</h1>
        <p className="text-sm">Last Updated: {new Date().toLocaleDateString()}</p>
        <p>The information and services provided by Seedream Innovations Inc. through Seedream ImagenBrainAi ("Service") are for general informational and creative purposes only. All information on the Service is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or generated content on the Service.</p>
        
        <h2>AI-Generated Content</h2>
        <p>The images and content generated by the Service are created by an artificial intelligence model. While we strive for high-quality and coherent outputs, the generated content may sometimes be unexpected, inaccurate, or offensive. We are not responsible for the content generated by users. You are responsible for the content you generate and how you use it.</p>

        <h2>No Professional Advice</h2>
        <p>The information provided by the Service is not a substitute for professional advice. Any action you take upon the information on this Service is strictly at your own risk. We will not be liable for any losses and damages in connection with the use of our Service.</p>
        
        <h2>External Links Disclaimer</h2>
        <p>The Service may contain links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us. WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY INFORMATION OFFERED BY THIRD-PARTY WEBSITES LINKED THROUGH THE SITE.</p>
        
        <h2>Limitation of Liability</h2>
        <p>Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the Service or reliance on any information provided on the Service. Your use of the Service and your reliance on any information on the Service is solely at your own risk.</p>
      </div>
    </>
  );
};

export default DisclaimerPage;
